# See https://www.loraserver.io/lora-app-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://loraserver_as_1:loraserver_as@postgresql/loraserver_as_1?sslmode=disable"

[redis]
url="redis://redis:6379/1"

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"
username=""
password=""

[application_server.api]
public_host="appserver:8001"


[application_server.external_api]
bind="0.0.0.0:8080"
tls_cert="/etc/lora-app-server/certs/http.pem"
tls_key="/etc/lora-app-server/certs/http-key.pem"
jwt_secret="verysecret"
